const{contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('electronAPI',{
  // Projection
  openProjection: (id)   =>ipcRenderer.invoke('open-projection',id),
  closeProjection:()     =>ipcRenderer.invoke('close-projection'),
  projectVerse:   (d)    =>ipcRenderer.invoke('project-verse',d),
  projectSong:    (d)    =>ipcRenderer.invoke('project-song',d),
  projectMedia:          (d) => ipcRenderer.invoke('project-media', d),
  sendLogoOverlay:       (d) => ipcRenderer.invoke('send-logo-overlay', d),
  logoOverlayDragUpdate: (d) => ipcRenderer.invoke('logo-overlay-drag-update', d),
  getPresets:            ()  => ipcRenderer.invoke('get-presets'),
  savePreset:            (d) => ipcRenderer.invoke('save-preset', d),
  deletePreset:          (id)=> ipcRenderer.invoke('delete-preset', id),
  getMedia:              ()  => ipcRenderer.invoke('get-media'),
  saveMedia:             (d) => ipcRenderer.invoke('save-media', d),
  importMediaFiles:      (d) => ipcRenderer.invoke('import-media-files', d),
  getMediaIntegrity:     ()  => ipcRenderer.invoke('get-media-integrity'),
  repairMediaLinks:      ()  => ipcRenderer.invoke('repair-media-links'),
  clearMediaCache:       ()  => ipcRenderer.invoke('clear-media-cache'),
  openFileLocation:      (d) => ipcRenderer.invoke('open-file-location', d),
  showUnsupportedDialog: (d) => ipcRenderer.invoke('show-unsupported-dialog', d),
  importPresentation:    (d) => ipcRenderer.invoke('import-presentation', d),
  getPresentations:      ()  => ipcRenderer.invoke('get-presentations'),
  getPresentationSlides: (d) => ipcRenderer.invoke('get-presentation-slides', d),
  deletePresentation:    (d) => ipcRenderer.invoke('delete-presentation', d),
  projectPresentationSlide:(d)=> ipcRenderer.invoke('project-presentation-slide', d),
  projectCreatedSlide:     (d)=> ipcRenderer.invoke('project-created-slide', d),
  openPresEditor:          (d)=> ipcRenderer.invoke('open-pres-editor', d),
  presEditorSaved:         (d)=> ipcRenderer.send('pres-editor-saved', d),
  pickPresFile:            (d)=> ipcRenderer.invoke('pick-pres-file', d),
  presentationEditorImportToLibrary: (d)=> ipcRenderer.invoke('import-presentation', d),
  addPresentationToScheduleFromEditor: (d)=> ipcRenderer.send('presentation-add-to-schedule', d),
  presBibleSearch:         (d)=> ipcRenderer.invoke('pres-bible-search', d),
  getCreatedPresentations: ()=> ipcRenderer.invoke('get-created-presentations'),
  saveCreatedPresentations:(d)=> ipcRenderer.invoke('save-created-presentations', d),
  showTimer:      (d)    =>ipcRenderer.invoke('show-timer',d),
  stopTimer:      ()     =>ipcRenderer.invoke('stop-timer'),
  timerScale:     (d)    =>ipcRenderer.invoke('timer-scale',d),
  showCaption:    (d)    =>ipcRenderer.invoke('show-caption',d),
  showAlert:      (d)    =>ipcRenderer.invoke('show-alert',d),
  clearProjection:()     =>ipcRenderer.invoke('clear-projection'),
  getDisplays:    ()     =>ipcRenderer.invoke('get-displays'),
  // Settings
  getSettings:    ()     =>ipcRenderer.invoke('get-settings'),
  saveSettings:   (s,opts)=>ipcRenderer.invoke('save-settings',s,opts||{}),
  openSettings:   (opts) =>ipcRenderer.invoke('open-settings', opts || {}),
  getSettingsOpenParams: () => ipcRenderer.invoke('get-settings-open-params'),
  // Adaptive management
  getAdaptiveDashboard:         ()    => ipcRenderer.invoke('get-adaptive-dashboard'),
  exportAdaptiveData:           ()    => ipcRenderer.invoke('export-adaptive-data'),
  importAdaptiveData:           (opts)=> ipcRenderer.invoke('import-adaptive-data', opts || {}),
  openAdaptiveManagement:       ()    => ipcRenderer.invoke('open-adaptive-management'),
  upsertAdaptiveSpeakerProfile: (d)   => ipcRenderer.invoke('upsert-adaptive-speaker-profile', d),
  deleteAdaptiveSpeakerProfile: (id)  => ipcRenderer.invoke('delete-adaptive-speaker-profile', id),
  upsertAdaptiveRule:           (d)   => ipcRenderer.invoke('upsert-adaptive-rule', d),
  deleteAdaptiveRule:           (id)  => ipcRenderer.invoke('delete-adaptive-rule', id),
  upsertAdaptiveVocab:          (d)   => ipcRenderer.invoke('upsert-adaptive-vocab', d),
  deleteAdaptiveVocab:          (id)  => ipcRenderer.invoke('delete-adaptive-vocab', id),
  approveAdaptiveSuggestion:    (id)  => ipcRenderer.invoke('approve-adaptive-suggestion', id),
  rejectAdaptiveSuggestion:     (id)  => ipcRenderer.invoke('reject-adaptive-suggestion', id),
  resetAdaptiveLearningData:    ()    => ipcRenderer.invoke('reset-adaptive-learning-data'),
  loadAdaptiveMemory:           ()    => ipcRenderer.invoke('load-adaptive-memory'),
  saveAdaptiveMemory:           (d)   => ipcRenderer.invoke('save-adaptive-memory', d),
  persistTranscriptSession:     (d)   => ipcRenderer.invoke('persist-transcript-session', d),
  persistTranscriptSessionEnd:  (d)   => ipcRenderer.invoke('persist-transcript-session-end', d),
  persistTranscriptChunk:       (d)   => ipcRenderer.invoke('persist-transcript-chunk', d),
  persistCorrectionEvents:      (d)   => ipcRenderer.invoke('persist-correction-events', d),
  loadLearningData:             ()    => ipcRenderer.invoke('load-learning-data'),
  // Transcripts
  saveTranscript: (d)    =>ipcRenderer.invoke('save-transcript',d),
  getTranscripts: ()     =>ipcRenderer.invoke('get-transcripts'),
  deleteTranscript:(id)  =>ipcRenderer.invoke('delete-transcript',id),
  openHistory:    ()     =>ipcRenderer.invoke('open-history'),
  loadDetectionReviewData: () => ipcRenderer.invoke('load-detection-review-data'),
  saveDetectionFeedback: (d) => ipcRenderer.invoke('save-detection-feedback', d),
  saveDetectionPhrase:   (d) => ipcRenderer.invoke('save-detection-phrase', d),
  // Songs
  getSongs:        ()       => ipcRenderer.invoke('get-songs'),
  saveSongs:       (songs)  => ipcRenderer.invoke('save-songs', songs),
  openHelpWindow:  ()       => ipcRenderer.invoke('open-help-window'),
  openSongManager: (opts)   => ipcRenderer.invoke('open-song-manager', opts || {}),
  importSongsFile:  (opts)   => ipcRenderer.invoke('import-songs-file', opts || {}),
  exportSongs:      (opts)   => ipcRenderer.invoke('export-songs', opts || {}),
  getSongLibraryInfo:()      => ipcRenderer.invoke('get-song-library-info'),
  backupSongLibrary:(opts)   => ipcRenderer.invoke('backup-song-library', opts || {}),
  importEasyworshipDataFolder: () => ipcRenderer.invoke('import-easyworship-data-folder'),
  importSmartSongSource:   (opts)   => ipcRenderer.invoke('import-smart-song-source', opts || {}),
  geniusSearch:     (q)    => ipcRenderer.invoke('genius-search', q),
  geniusFetchLyrics:(d)    => ipcRenderer.invoke('genius-fetch-lyrics', d),
  backupFullAppData:    () => ipcRenderer.invoke('backup-full-appdata'),
  restoreFullAppData:   () => ipcRenderer.invoke('restore-full-appdata'),
  // Schedule
  saveSchedule:      (data)   => ipcRenderer.invoke('save-schedule', data),
  saveScheduleAs:    (data)   => ipcRenderer.invoke('save-schedule-as', data),
  openScheduleDialog:()       => ipcRenderer.invoke('open-schedule-dialog'),
  loadScheduleFile:  (file)   => ipcRenderer.invoke('load-schedule-file', file),
  consumePendingScheduleOpen: () => ipcRenderer.invoke('consume-pending-schedule-open'),
  loadSchedules:     ()       => ipcRenderer.invoke('load-schedules'),
  deleteSchedule:    (file)   => ipcRenderer.invoke('delete-schedule', file),
  // Themes
  getThemes:      ()     =>ipcRenderer.invoke('get-themes'),
  saveThemes:     (t)    =>ipcRenderer.invoke('save-themes',t),
  openThemeDesigner:(d)  =>ipcRenderer.invoke('open-theme-designer', d),
  getThemeDesignerParams:()=>ipcRenderer.invoke('get-theme-designer-params'),
  pickBgMedia:       (d) =>ipcRenderer.invoke('pick-bg-media', d),
  // Export
  exportFile:     (opts) =>ipcRenderer.invoke('export-file',opts),
  exportTranscript:(opts)=>ipcRenderer.invoke('export-transcript',opts),
  importNotes:     ()    =>ipcRenderer.invoke('import-notes'),
  // Bible data
  loadBibleData:        ()              => ipcRenderer.invoke('load-bible-data'),
  getInstalledVersions: ()              => ipcRenderer.invoke('get-installed-versions'),
  saveBibleVersion:     (trans, data)   => ipcRenderer.invoke('save-bible-version', trans, data),
  deleteBibleVersion:   (trans)         => ipcRenderer.invoke('delete-bible-version', trans),
  importTranslation:    ({abbrev, data})=> ipcRenderer.invoke('save-bible-version', abbrev, data),
  deleteTranslation:    (trans)         => ipcRenderer.invoke('delete-bible-version', trans),
  // Transcription — PCM audio bridge (renderer → main → transcription)
  pushAudioPcm:   (pcmBuffer) => ipcRenderer.invoke('push-audio-pcm', pcmBuffer),
  onTranscript:   (cb) => {
    const sub = (_, text) => cb(text);
    ipcRenderer.on('transcript-result', sub);
    return () => ipcRenderer.removeListener('transcript-result', sub);
  },
  // Whisper local server
  whisperStatus:  ()       => ipcRenderer.invoke('whisper-status'),
  whisperStart:   (model)  => ipcRenderer.invoke('whisper-start', model),
  whisperStop:    ()       => ipcRenderer.invoke('whisper-stop'),
  startWhisper:   (model)  => ipcRenderer.invoke('whisper-start', model),
  reinforceWhisper: (data) => ipcRenderer.invoke('whisper-reinforce', data),
  setWhisperSource: (src)  => ipcRenderer.invoke('set-whisper-source', src),
  whisperDiagnostics: ()   => ipcRenderer.invoke('whisper-diagnostics'),
  runWhisperSetup: ()      => ipcRenderer.invoke('run-whisper-setup'),
  getWhisperModels: ()     => ipcRenderer.invoke('get-whisper-models'),
  downloadWhisperModel: (id) => ipcRenderer.invoke('download-whisper-model', id),
  ndiStart:  ()  => ipcRenderer.invoke('ndi-start'),
  ndiStop:   ()  => ipcRenderer.invoke('ndi-stop'),
  ndiStatus: ()  => ipcRenderer.invoke('ndi-status'),
  getCurrentRenderState: () => ipcRenderer.invoke('get-current-render-state'),
  // Utils
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  // License
  getRegistrationStatus: () => ipcRenderer.invoke('get-registration-status'),
  getLicenseStatus: () => ipcRenderer.invoke('get-license-status'), // legacy compat
  sendRegistrationEmail: (fullName, email, church) => ipcRenderer.invoke('send-registration-email', fullName, email, church),
  getEmailSentState:     () => ipcRenderer.invoke('get-email-sent-state'),
  getTimerState:     ()     => ipcRenderer.invoke('get-timer-state'),
  timerFlashSpeed: (data)  => ipcRenderer.invoke('timer-flash-speed', data),
  isTimerStandalone: ()    => ipcRenderer.invoke('is-timer-standalone'),
  showClock: (data)        => ipcRenderer.invoke('show-clock', data),
  hideClock: ()            => ipcRenderer.invoke('hide-clock'),
  getClockState: ()        => ipcRenderer.invoke('get-clock-state'),
  setProjectionBg: (data)  => ipcRenderer.invoke('set-projection-bg', data),
  pickBgFile:  (type)      => ipcRenderer.invoke('pick-bg-file', type),
  setTranscriptUnsaved: (v) => ipcRenderer.send('transcript-unsaved-state', v),
  quitConfirmed:     ()     => ipcRenderer.send('quit-confirmed'),
  quitCancelled:     ()     => ipcRenderer.send('quit-cancelled'),
  lrclibSearch:      (d)    => ipcRenderer.invoke('lrclib-search', d),
  lrclibFetchLyrics: (d)    => ipcRenderer.invoke('lrclib-fetch-lyrics', d),
  importLicenseFile: ()    => ipcRenderer.invoke('import-license-file'),
  consumePendingLicenseImport: () => ipcRenderer.invoke('consume-pending-license-import'),
  activateRegistration: (fullName, email, token, church) => ipcRenderer.invoke('activate-registration', fullName, email, token, church),
  getHardwareId:     ()    => ipcRenderer.invoke('get-hardware-id'),
  copyToClipboard: (text) => ipcRenderer.invoke('copy-to-clipboard', text),
  openCountdownWindow: () => ipcRenderer.invoke('open-countdown-window'),
  openLicenseWindow: () => ipcRenderer.invoke('open-license-window'),
  openBibleManager: () => ipcRenderer.invoke('open-bible-manager'),
  openPresentationEditor: (opts) => ipcRenderer.invoke('open-presentation-editor', opts || {}),
  saveServiceArchive: (data) => ipcRenderer.invoke('save-service-archive', data),
  searchServiceArchive: (query) => ipcRenderer.invoke('search-service-archive', query),
  getServiceArchiveIndex: () => ipcRenderer.invoke('get-service-archive-index'),
  loadServiceArchiveItem: (archiveId) => ipcRenderer.invoke('load-service-archive-item', archiveId),
  getAutoServiceSuggestions: (opts) => ipcRenderer.invoke('get-auto-service-suggestions', opts || {}),
  buildAutoServiceSchedule: (opts) => ipcRenderer.invoke('build-auto-service-schedule', opts || {}),
  getLiveSmartSuggestions: (opts) => ipcRenderer.invoke('get-live-smart-suggestions', opts || {}),
  generateSermonIntelligence: (opts) => ipcRenderer.invoke('generate-sermon-intelligence', opts || {}),
  getAnalyticsDashboard: (opts) => ipcRenderer.invoke('get-analytics-dashboard', opts || {}),
  saveClipPackage: (opts) => ipcRenderer.invoke('save-clip-package', opts || {}),
  send: (channel, ...args) => {
    const allowed = ['open-ndi-panel', 'presentation-add-to-schedule'];
    if (!allowed.includes(channel)) return false;
    ipcRenderer.send(channel, ...args);
    return true;
  },
  // Info/tools
  getAppInfo:        ()     => ipcRenderer.invoke('get-app-info'),
  getRemoteInfo:     ()     => ipcRenderer.invoke('get-remote-info'),
  getRemoteStatus:   ()     => ipcRenderer.invoke('get-remote-status'),
  getRemoteRuntimeStatus: () => ipcRenderer.invoke('get-remote-runtime-status'),
  getNetworkAdapters:()     => ipcRenderer.invoke('get-network-adapters'),
  setNetworkAdapter: (name) => ipcRenderer.invoke('set-network-adapter', name),
  toggleRemote:      (en)   => ipcRenderer.invoke('toggle-remote', en),
  startRemote:       ()     => ipcRenderer.invoke('start-remote'),
  stopRemote:        ()     => ipcRenderer.invoke('stop-remote'),
  showRemoteUrl:     ()     => ipcRenderer.invoke('show-remote-url'),
  // Events main→renderer
  on:(channel,cb)=>{
    const allowed=[
      'projection-opened','projection-closed',
      'shortcut-go-live','shortcut-next','shortcut-prev','shortcut-clear',
      'show-verse','show-song','show-media','clear-verse',
      'show-timer','stop-timer','timer-scale','show-caption','show-alert',
      'http-server-started',
      'remote-present','remote-queue-add','remote-set-translation','remote-present-song','remote-present-media',
      'remote-control',
      'open-settings-modal','settings-saved','bible-versions-updated','ndi-status','open-ndi-panel','open-sermon-notes',
      'songs-saved',
      'transcript-result','transcript-no-key','whisper-status','whisper-setup-needed','whisper-setup-result','whisper-model-progress','whisper-model-downloaded',
      'menu-schedule-new','menu-schedule-save','menu-schedule-save-as',
      'menu-schedule-open','menu-schedule-export','menu-schedule-import',
      'menu-schedule-load-file',
      'menu-preset-save','menu-preset-load','menu-preset-manage',
      'menu-show-occ',
      'app-ready',
      'menu-show-getstarted',
      'show-created-slide',
      'pres-editor-load', 'pres-editor-saved',
      'show-presentation-slide',
      'render-state',
      'logo-overlay',
      'logo-overlay-drag-update',
      'theme-designer-open',
      'themes-updated',
      'song-manager-new-song','song-manager-open-song','license-file-opened','registration-complete','display-warning','timer-state-sync','timer-stopped','timer-flash-speed','set-projection-bg','show-clock','hide-clock','confirm-quit-with-transcript',
    ];
    if(!allowed.includes(channel)) return()=>{};
    const sub=(_,...args)=>cb(...args);
    ipcRenderer.on(channel,sub);
    return()=>ipcRenderer.removeListener(channel,sub);
  },
  platform:process.platform,
  isElectron:true,
});
